name: Build and Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: us-west-2  # Specify your AWS region here

    - name: Build, Tag, and Push Docker image to ECR
      run: |
        # Build your Docker image
        docker build -t myapp .

        # Tag it with the ECR repository URI
        docker tag myapp:latest 211125762589.dkr.ecr.us-west-2.amazonaws.com/myapp:latest

        # Push it to ECR
        docker push 211125762589.dkr.ecr.us-west-2.amazonaws.com/myapp:latest
      env:
        AWS_DEFAULT_REGION: us-west-2  # Ensure the region is specified in environment variables
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}