name: Build and Deploy to AWS ECR

on:
  push:
    branches:
      - main  # Set this to your production branch, e.g., main or master

jobs:
  build-and-push:
    name: Build and Push Docker image to AWS ECR
    runs-on: ubuntu-latest  # The runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Docker image to ECR
      run: |
        # Build your Docker image
        docker build -t counter_web .

        # Tag it with the ECR repository URI
        docker tag counter_web:latest 211125762589.dkr.ecr.us-west-2.amazonaws.com/counter_web:latest

        # Push it to ECR
        docker push 211125762589.dkr.ecr.us-west-2.amazonaws.com/counter_web:latest
